### ISSUE TITLE
Cannot assign 'damage' as Resource for Token...

### ISSUE THREAD

**Issue by WildBillLives** [OctarineSourcerer/cyberpunk2020#61]
In the latest release (v0.2.2) (using Foundry v0.7.9) you can no longer assign 'damage' as a resource for an actor token. In the previous release this worked fine - in the current version if you try to assign the 'damage' value to either the Bar 1 or Bar 2 resource value and click "Update Token" it will _seem_ to accept it but will not actually assign it (_i.e. if you open the token again the value is shown as unassigned to either bar_).

Checking the (F12) console I can see no error messages shown for this, so no help there I am afraid...

**Comment by drowzero0** [comment]
it has no value as you can see:
![image](https://user-images.githubusercontent.com/62395017/115453988-92c57780-a220-11eb-8b63-8489d9511453.png)
here for damage
and the following is with a value:
![image](https://user-images.githubusercontent.com/62395017/115454044-a2dd5700-a220-11eb-8e19-8333c028136b.png)

if i remember correctly i never saw this working. tested it in 0.1.2 last time, but didnt know it worked between those versions and havent seen a issue for solving this.

but if this could work, it would be nice for sure :D

**Comment by WildBillLives** [comment]
Hum - I could be wrong on the previous working bit as I run a number of games on Foundry and sometimes they all merge together into one big blur :-)

But, as you say, it would be quite helpful to be able to adjust damage on the token, especially for unlinked tokens (NPCs, etc). If nothing else I guess perhaps consider this a feature request?

Thanks!

**Comment by OctarineSourcerer** [comment]
I'll look into it :)

**Comment by OctarineSourcerer** [comment]
Okay, so you're entirely right - other things work, but damage doesn't. That's partially because the thing I was using for the wound tracker only deals in strings, so the token UI saw damage as a word rather than a number.

That should be fixed in ee5407c! It's in the develop branch at the moment, but will be in the next release (just wanna see if I can bundle a few things together for the release, shouldn't be long to wait). Have tested, seems to work on the resource bars

PS: I hadn't actually used the token resource bars before. Woah that's cool.

**Comment by drowzero0** [comment]
existing actors/token are not able to set damage as a bar since it still shows no value
![image](https://user-images.githubusercontent.com/62395017/115617162-59107180-a2f1-11eb-88d3-7a143c5ca239.png)

even updating the world with:
game.cyberpunk.migrateWorld()
did not help here.
also restarting the node did not update the availability for existing actors.

for some of my non actor tokens there is not even an option to set damage for bars:
![image](https://user-images.githubusercontent.com/62395017/115617617-e3f16c00-a2f1-11eb-9414-a1e74edb798b.png)

**Comment by OctarineSourcerer** [comment]
Huh. Could you go to the settings in the top right, and tell me what version number is to the right of "Cyberpunk 2020"? Creating new actors is working for me. 

Let me know if using the wound tracker to adjust fixes it too :) 

(I've tried adding a bit of a migration for this now, if you wanna try migrating again)

**Comment by drowzero0** [comment]
version of foundry & cyberpunk2020:
![image](https://user-images.githubusercontent.com/62395017/115619500-3af84080-a2f4-11eb-952f-464dd25e53cb.png)

with new actors it is working fine. but not with existing ones.

the above shown "cultist" sheet is completly broken (worked last on saturday evening) now i am unable to close it. only reloading the site works.

**Comment by OctarineSourcerer** [comment]
Huuuuh. By completely broken, do you mean that damage doesn't work, or something else being broken?

**Comment by drowzero0** [comment]
ok adding and removing dmg from the woundtracker sets up the value. 
after this i am able to use damage for bars.

for the cultist token it is the same.
the listed item damage showed up after adding a wound on the tracker. 
now the token is able to get damage set for bars and i am able to close the actor.sheet again

**Comment by OctarineSourcerer** [comment]
Whew that's good to hear. I should really have more time before features in develop being pushed to release...

**Comment by drowzero0** [comment]
it now looks like this for me:
![image](https://user-images.githubusercontent.com/62395017/115620636-b6a6bd00-a2f5-11eb-82a7-fba456be0a83.png)

this isnt kind of a "healthbar"
for a healtbar it would be nice if it was able to show 40HP as max and then reducing it with every added woundpoint.
so like in the above shown image it wouldnt be 6 woundpoints but 34HP left 
not sure how much work this would be?
guess it will create a bar itself if there is a max value set up:
![image](https://user-images.githubusercontent.com/62395017/115621074-506e6a00-a2f6-11eb-82b1-ccf4cf7a7c0a.png)
but not sure if this does the trick.

**Comment by OctarineSourcerer** [comment]
Yes, that's correct. Regular integer values such as 0 or 5 will be shown as just a number. Objects with a `value` and a `max`; eg `"damage": { value: 4; max: 40 }` will be shown as a bar. Currently damage is tracked as just a number.

I do agree that a bar with a maximum would be an improvement, giving a level of context to amounts of damage, but with one caveat: most games have HP instead of damage, where more full is healthier, and especially around the middle (20/40) some people might mistake it for HP instead, even though cyberpunk works the other way around. I might add it as something you can configure! Here's the issue I've made for tracking it, as it's a slightly separate issue: https://github.com/OctarineSourcerer/cyberpunk2020/issues/63

By the way, might be a bit quiet on this front for several days; I'm participating in the Ludum Dare Game Jam. Feel free to raise issues in the meantime! If there are any breaking bugs that pop up I can see how fast I can deal with them.
